trigger:
  - none
stages:
  - stage: iOSStage
    pool:
      vmImage: macos-latest
    dependsOn: []
    displayName: iOS
    jobs:
      - job: iOSJob
        displayName: iOS
        steps:
          - task: InstallAppleCertificate@2
            displayName: Install certificate
            inputs:
              certSecureFile: goowid.p12
              certPwd: GreenSignals$24
              keychain: temp
          - task: InstallAppleProvisioningProfile@1
            displayName: Install provisioning file
            inputs:
              provisioningProfileLocation: secureFiles
              provProfileSecureFile: Goowid_Authenticator.mobileprovision
          - task: Bash@3
            displayName: '[Flutter] Configure Flutter'
            inputs:
              targetType: 'inline'
              script: |
                /Users/runner/hostedtoolcache/flutter doctor -v
                /Users/runner/hostedtoolcache/flutter config --no-analytics

          - task: Bash@3
            displayName: '[Flutter] Build project environment'
            inputs:
              targetType: 'inline'
              script: |
                /Users/runner/hostedtoolcache/flutter pub get
                /Users/runner/hostedtoolcache/flutter pub global activate junitreport

          - task: Bash@3
            displayName: '[Flutter] Flutter coverage'
            inputs:
              targetType: 'inline'
              script: |
                pip install lcov_cobertura
                /Users/runner/hostedtoolcache/flutter test --coverage
                python -m lcov_cobertura coverage/lcov.info -o coverage/coverage.xml
                
          - task: Bash@3
            displayName: '[Flutter] Flutter build'
            inputs:
              targetType: 'inline'
              script: |
                /Users/runner/hostedtoolcache/flutter build ios --release --no-codesign --build-number $(Build.BuildId)

          - task: CocoaPods@0
            inputs:
              workingDirectory: '$(Build.SourcesDirectory)/ios/Flutter'
              forceRepoUpdate: true
          - task: Xcode@5
            inputs:
              actions: 'build'
              scheme: ''
              sdk: 'iphoneos'
              configuration: 'Release'
              xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
              xcodeVersion: 'default'
              signingOption: 'manual'
              signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
              provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
              packageApp: true
          - task: CopyFiles@2
            inputs:
              contents: '**/*.ipa'
              targetFolder: '$(build.artifactStagingDirectory)'
              overWrite: true
              flattenFolders: true
          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: '$(build.artifactStagingDirectory)'
              artifactName: 'drop'
              publishLocation: 'Container'
