trigger:
  - none

jobs:
  - job: ios
    pool:
      vmImage: "macos-latest"
    variables:
      - group: secrets
      - group: general
      - name: configuration
        value: "Release"
      - name: sdk
        value: "iphoneos"
      - name: iosReleaseDir
        value: $(Build.SourcesDirectory)/output/$(sdk)/$(configuration)
      - name: ipaFile
        value: $(iosReleaseDir)/hello_world_counter_app.ipa
    steps:
      - task: FlutterInstall@0
        displayName: "Install Flutter"
        inputs:
          mode: "auto"
          channel: "stable"
          version: "latest"
      - task: FlutterBuild@0
        displayName: "Flutter Build Apps - iOS"
        inputs:
          target: "ios"
          buildName: "$(Build.BuildNumber)"
          entryPoint: "lib/main.dart"
          iosCodesign: false
      - task: InstallAppleCertificate@2
        displayName: "Install Apple p12 cert"
        inputs:
          certSecureFile: "goowid_ajiil.p12"
          certPwd: GreenSignals$24
          keychain: "temp"

      - task: InstallAppleProvisioningProfile@1
        displayName: "Install Apple Mobile Provisioning Profile"
        inputs:
          provisioningProfileLocation: "secureFiles"
          provProfileSecureFile: "Goowid_Auth.mobileprovision"
      - task: Xcode@5
        displayName: "Code Sign ipa for Distribution"
        inputs:
          actions: "build"
          scheme: "Runner"
          sdk: 'iphoneos'
          configuration: 'Release'
          xcWorkspacePath: "ios/Runner.xcworkspace"
          xcodeVersion: "default"
          packageApp: true
          signingOption: "manual"
          signingIdentity: "$(APPLE_CERTIFICATE_SIGNING_IDENTITY)"
          provisioningProfileUuid: "$(APPLE_PROV_PROFILE_UUID)"