trigger:
  - none
stages:
  - stage: iOSStage
    pool:
      vmImage: macos-latest
    dependsOn: []
    displayName: iOS
    jobs:
      - job: iOSJob
        displayName: iOS
        steps:
          - task: InstallAppleCertificate@2
            displayName: Install certificate
            inputs:
              certSecureFile: goowid.p12
              certPwd: GreenSignals$24
              keychain: temp
          - task: InstallAppleProvisioningProfile@1
            displayName: Install provisioning file
            inputs:
              provisioningProfileLocation: secureFiles
              provProfileSecureFile: Goowid.mobileprovision
          - task: FlutterInstall@0
            displayName: Install Flutter SDK
            inputs:
              mode: auto
              channel: stable
              version: latest
          - task: FlutterCommand@0
            displayName: Run Flutter diagnostics
            inputs:
              projectDirectory: .
              arguments: doctor -v
          - task: FlutterBuild@0
            displayName: Build application
            inputs:
              target: ipa
              projectDirectory: $(Build.SourcesDirectory)
          - task: FlutterTest@0
            displayName: Run unit tests
            inputs:
              generateCodeCoverageReport: true
              projectDirectory: $(Build.SourcesDirectory)
          - task: CopyFiles@2
            displayName: Copy app to staging directory
            inputs:
              sourceFolder: $(Agent.BuildDirectory)
              contents: '**/ipa/*.ipa'
              targetFolder: $(Build.StagingDirectory)
              flattenFolders: true
          - task: PublishBuildArtifacts@1
            displayName: Publish IPA file
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              ArtifactName: IPA
              publishLocation: Container
