trigger:
  - none
stages:
  - stage: iOSStage
    pool:
      vmImage: macos-latest
    dependsOn: []
    displayName: iOS
    jobs:
      - job: iOSJob
        displayName: iOS
        steps:
          - task: InstallAppleCertificate@2
            displayName: Install certificate
            inputs:
              certSecureFile: goowid_ajiil.p12
              certPwd: GreenSignals$24
              keychain: temp
              deleteCert: true
          - task: InstallAppleProvisioningProfile@1
            displayName: Install provisioning file
            inputs:
              provisioningProfileLocation: secureFiles
              provProfileSecureFile: Goowid_Auth.mobileprovision
              removeProfile: true
          - task: Xcode@5
            displayName: "Code sign ipa for Distribution"
            inputs:
              actions: "build"
              xcWorkspacePath: "**/Runner.xcworkspace"
              scheme: "Runner"
              sdk: "iphoneos"
              configuration: "release"
              packageApp: true
              signingOption: "manual"
              signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
              provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'      
          - task: CopyFiles@2
            inputs:
              contents: '**/*.ipa'
              targetFolder: '$(build.artifactStagingDirectory)'
              OverWrite: true

          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: 'drop'
